# Generated by Django 6.0.6 on 2026-09-03 16:52

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compress_photos', models.BooleanField(default=True, help_text='Pré-seleciona a compressão ao enviar fotos para este memo. Desmarque para guardar os arquivos originais.', verbose_name='comprimir fotos por padrão')),
                ('metadata_fields', models.JSONField(blank=True, default=core.utils.default_metadata_fields, help_text='Pré-seleciona quais metadados serão lidos das fotos enviadas para este memo.', verbose_name='metadados por padrão')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to=settings.AUTH_USER_MODEL)),
                ('shared_edit', models.ManyToManyField(blank=True, related_name='shared_memos_edit', to=settings.AUTH_USER_MODEL, verbose_name='pode editar')),
                ('shared_view', models.ManyToManyField(blank=True, related_name='shared_memos_view', to=settings.AUTH_USER_MODEL, verbose_name='pode visualizar')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/', verbose_name='arquivo')),
                ('taken_at', models.DateTimeField(help_text='Extraída dos metadados da foto quando disponível.', verbose_name='data')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('metadata_fields', models.JSONField(blank=True, default=core.utils.default_metadata_fields, verbose_name='metadados habilitados')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='core.memo', verbose_name='memo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_photos', to=settings.AUTH_USER_MODEL, verbose_name='compartilhada com')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
